version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=["http://54.167.37.145:8080", "http://localhost:8080", "http://localhost:8000"]
    restart: always
